#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate a systematic DRAWEXE test group ("seamless") that exercises the fillet
builder over the shapes ChFi3d cares about.

The group is a *differential* suite: the cases carry no golden values.  Each case
prints deterministic geometry (validity, volume/area, bounding box, sub-shape
counts) and the two kernels' logs are diffed against each other.  Any change in
any printed digit is a difference.

Grids
  prim_single  one fillet on one edge of one primitive, several radii
               (box, cylinder, cone, sphere, torus -- periodic and not)
  box_corner   fillets on edge sets meeting at a corner with 2, 3 and 4+ edges
  seam_rib     a radial rib fused onto a periodic primitive, rotated through a
               full turn so the seam falls at every angle relative to the rib,
               then every edge filleted.  This is the geometry of the reported
               defect, swept.
"""
import os
import sys

HEADER = """## generated by gen_seamless_group.py -- differential fillet regression
## {title}
"""

# Primitives: name -> (draw command building shape "s", number of edges to try)
PRIMS = {
    'box':      ('box s 10 14 18',                 12),
    'cylinder': ('pcylinder s 8 20',                3),
    'cone':     ('pcone s 9 4 18',                  3),
    'sphere':   ('psphere s 9',                     3),
    'torus':    ('ptorus s 12 4',                   2),
}

# Periodic primitives used for the seam sweep (they all carry a u-seam).
SEAM_PRIMS = {
    'cylinder': 'pcylinder s 10 30',
    'cone':     'pcone s 12 6 30',
    'sphere':   'psphere s 12',
    'torus':    'ptorus s 14 5',
}

REPORT = """
if { [isdraw result] } {
    puts "RESULT_BUILT yes"
    puts "CHECKSHAPE [checkshape result]"
    vprops result 1.e-6
    sprops result 1.e-6
    bounding result
    nbshapes result
} else {
    puts "RESULT_BUILT no"
}

puts "TEST COMPLETED"
"""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)


def gen_prim_single(root):
    """One edge, one radius, one primitive."""
    d = os.path.join(root, 'prim_single')
    n = 0
    for prim, (mk, nedges) in sorted(PRIMS.items()):
        for edge in range(1, nedges + 1):
            for radius in ('0.5', '1.5', '3.0'):
                name = '%s_e%d_r%s' % (prim, edge, radius.replace('.', ''))
                body = HEADER.format(title='%s, edge %d, radius %s' % (prim, edge, radius))
                body += """
{mk}
explode s e
if {{ ! [isdraw s_{edge}] }} {{
    puts "NO_SUCH_EDGE s_{edge}"
    puts "TEST COMPLETED"
    return
}}
if {{ [catch {{ blend result s {radius} s_{edge} }} err] }} {{
    puts "BLEND_RAISED $err"
}}
""".format(mk=mk, edge=edge, radius=radius)
                body += REPORT
                write(os.path.join(d, name), body)
                n += 1
    return n


def gen_box_corner(root):
    """Edge sets meeting at a corner: 2, 3 and 4+ edges."""
    d = os.path.join(root, 'box_corner')
    n = 0
    # Edge index sets of a Draw box; indices are stable for a given box command.
    sets = {
        'two':    [(1, 2), (3, 4), (5, 6), (1, 5), (2, 6), (9, 10)],
        'three':  [(1, 2, 3), (1, 5, 9), (2, 6, 10), (4, 8, 12), (3, 7, 11)],
        'four':   [(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12), (1, 3, 5, 7)],
        'six':    [(1, 2, 3, 4, 5, 6)],
        'all':    [tuple(range(1, 13))],
    }
    for kind, groups in sorted(sets.items()):
        for gi, edges in enumerate(groups, 1):
            for radius in ('0.5', '1.5'):
                name = 'box_%s%d_r%s' % (kind, gi, radius.replace('.', ''))
                args = ' '.join('%s s_%d' % (radius, e) for e in edges)
                body = HEADER.format(
                    title='box, %d edges %s, radius %s' % (len(edges), list(edges), radius))
                body += """
box s 10 14 18
explode s e
if {{ [catch {{ blend result s {args} }} err] }} {{
    puts "BLEND_RAISED $err"
}}
""".format(args=args)
                body += REPORT
                write(os.path.join(d, name), body)
                n += 1
    return n


def gen_seam_rib(root, angles, radii):
    """A radial rib fused onto a periodic primitive, swept around the seam."""
    d = os.path.join(root, 'seam_rib')
    n = 0
    for prim, mk in sorted(SEAM_PRIMS.items()):
        for ang in angles:
            for radius in radii:
                name = '%s_a%03d_r%s' % (prim, ang, radius.replace('.', ''))
                body = HEADER.format(
                    title='%s with radial rib at %d deg, all edges filleted r=%s'
                          % (prim, ang, radius))
                body += """
{mk}
# a radial rib; at angle 0 it sits exactly on the u-seam of the primitive
box rib 8 5 7
ttranslate rib 6 -2.5 -3.5
trotate rib 0 0 0 0 0 1 {ang}
if {{ [catch {{ bfuse fused s rib }} err] }} {{
    puts "FUSE_RAISED $err"
    puts "TEST COMPLETED"
    return
}}
renamevar fused s
# explode returns the list of names it created (DBRep.cxx: di.AppendElement)
set edges [explode s e]
puts "EDGE_COUNT [llength $edges]"
set cmd "blend result s"
foreach e $edges {{ append cmd " {radius} $e" }}
if {{ [catch {{ eval $cmd }} err] }} {{
    puts "BLEND_RAISED $err"
}}
""".format(mk=mk, ang=ang, radius=radius)
                body += REPORT
                write(os.path.join(d, name), body)
                n += 1
    return n


def main():
    root = sys.argv[1]
    angles = list(range(0, 360, 10))          # 36 angles, full turn
    radii = ('0.8',)

    counts = {}
    counts['prim_single'] = gen_prim_single(root)
    counts['box_corner'] = gen_box_corner(root)
    counts['seam_rib'] = gen_seam_rib(root, angles, radii)

    # group-level begin/end and grid list
    write(os.path.join(root, 'begin'), """# differential fillet regression, seamless project
# 10 minutes of CPU per case; a case killed by this limit is a result, not a stall.
cpulimit 600
if { [array get Draw_Groups "TOPOLOGY Feature commands"] == "" } {
    pload TOPTEST
}
if { [info exists imagedir] == 0 } { set imagedir . }
if { [info exists test_image ] == 0 } { set test_image photo }
""")
    write(os.path.join(root, 'end'), '')
    write(os.path.join(root, 'grids.list'),
          '001 prim_single\n002 box_corner\n003 seam_rib\n')

    total = sum(counts.values())
    for k in sorted(counts):
        print('%-12s %4d cases' % (k, counts[k]))
    print('%-12s %4d cases' % ('TOTAL', total))


if __name__ == '__main__':
    main()
